# -*- coding: utf-8 -*-
"""
Currículo oficial del Bachillerato en Artes — Mención Artes Visuales — MINERD
Extraído del Plan de Estudios oficial de la Dirección de Modalidad en Artes.
Segundo Ciclo del Nivel Secundario (4to, 5to, 6to).
"""

CURRICULUM_ARTES_VISUALES = {
    'Teoría e Historia de las Artes V isuales Latinoamericana y Dominicana': {
        'modulo': 'Bachillerato en Artes — Mención Artes Visuales',
        'horas': '4',
        'elemento_competencia': 'Analiz a los orígenes, característica y evolución del arte Latinoamericano y Dominicano desde la época precolombina hasta la actualidad, incorporando sus técnicas , temáticas y sus valores estéticos y formales a su expresión visual.',
        'rae': ['Argumenta con claridad acerca de los orígenes e identidad del arte en Latinoamérica y República Dominicana, su importancia y la influencia de otras culturas.', 'Establece una secuencia cronológica del desarrollo evolutivo de las culturas Latinoam ericanas y Dominicanas, de forma gráfica a través mapas conceptuales y líneas de tiempo.', 'Describe las características, contexto político, social y religioso de las culturas que protagonizaron el Arte Latinoamericano y Dominicano en su devenir histórico.', 'Selecciona imágenes de obras destacadas donde se identifican las características estéticas, técnicas, tendencias, géneros, estilos y las grandes temáticas de las obras representativas en la arquitectura, dibujo, pintura, escultura etc. del arte Latinoame ricano y Dominicano desde la etapa precolombina hasta la época actual.', 'Realiza cuadros comparativos donde establece las diferencias y similitudes de las características de la arquitectura, pintura y escultura surgidas en la cuna de', 'Plan de estudio de la Mención Artes Visuales Dirección de la Modalidad en Artes', 'las civilizaciones del Continente Europeo y las culturas originarias en Latinoamérica.', 'Participa en la elaboración proyectos de reinterpretación de obras a partir de los referentes del arte Latinoamericano y Dominicano haciendo uso de las características, técnicas , valores estéticos y formales imprimiendo su propia inventiva y expresión visual .'],
        'conceptuales': ['Introducción a los orígenes e identidad del arte Latinoamericano y Dominicano y sus influencias.', 'Cronología y culturas que habitaron en Latinoamérica (Centroamérica y el Caribe), sus etapas evolutivas, contexto histórico, social, político y religioso: 1- Arte prehispánico en Mesoamérica.', 'Etapas del arte prehispánico en Mesoamérica. Olmecas, zapote cas, mayas, Los Inca, Los Aztecas. 2- El Arte Latinoamericano: Centro América, Sur América y el Caribe. Períodos, características y artistas reconocidos y sus obras más destacadas.', 'Etapas: Arte Indígena o Precolombino, Arte Colonial, Arte Post Colonial, Arte Latino Americano del XX.', 'Surgimiento del concepto de “Arte Latinoamericano”, búsqueda de identidad, autores relevantes del Arte Latinoamericano y Dominicano (IX - XX). 3- El Arte Dominicano:', 'Etapas: Sus orígenes Precolombino , Arte Colonial, Arte de la Primera República, Arte de la Segunda República y Arte Actual.', 'Características estéticas, técnicas y las grandes temáticas de las obras representativas en la arquitectura, dibujo, pintura, escultura etc. del Arte Latinoamerica no y Dominicano desde la Etapa Precolombina hasta la Época Actual.'],
        'procedimentales': ['Identificar las etapas y características y los ejemplos más sobresalientes desde el Arte Pre colombino hasta la modernidad del Arte Latinoamericano y Dominicano.', 'Construir mapas conceptuales y líneas de tiempo identificando característica , contexto histórico, político, social, religioso de las grandes culturas que protagonizaron el Arte Latinoamericano y Do minicano.', 'Realizar tablas de análisis que contengan las principales características estéticas, técnicas y las grandes temáticas de las obras representativas en la arquitectura, dibujo, pintura, escultura etc. del arte Latinoamericano y Dominicano desde l a Etapa Precolombina hasta la Época Actual.', 'Plan de estudio de la Mención Artes Visuales Dirección de la Modalidad en Artes', 'Establecer diferencia y similitudes de las características de la arquitectura, pintura y escultura surgidas en la cuna de las civilizaciones del Continente Europeo y las culturas originarias en Latinoamérica.', 'Comparar los valores estéticos de cada época, destacando tendencias, géneros y estilos.', 'Comentar las principales obras del Arte Latinoamericano y Dominicano.', 'Reinterpretar obras a partir de los referen tes del Arte Latinoamericano y Dominicano ( características, valores estéticos y formales) .'],
        'actitudinales': ['Reflexión y juicio crítico.', 'Disciplina y orden.', 'Actitud curiosa y atenta.', 'Respeto por la expresión del arte de cada cultura.', 'Aprecia el entorno espacial urbano y arquitectónico.', 'Concentración e interés por la lectura.', 'Valoración de los aportes de las culturas que habitaron arte Latinoamericano y Dominicano .', 'Interés por los aportes y obras de los autores más destacados del Arte Latinoamericano y Dominicano.'],
    },
    'Fundamentos de la Semiótica Visual': {
        'modulo': 'Bachillerato en Artes — Mención Artes Visuales',
        'horas': '2',
        'elemento_competencia': 'Reconoce los elementos expresivos del signo visual, semióticos, e indaga sobre las relaciones entre el contenido y la forma del signo, en la creación de significados, contextualizando las obras de su preferencia en su sentido cultural e histórico y la influencia de las tecnologías recientes, la fotografía, el cine, la televisión y el Internet. Resultados del Aprendiz aje Esperados 1. Identifica la relación signo -significado en diversas muestras de imágenes y obras visuales. 2. Argumenta sobre los tipos de signos de acuerdo a las teorías de Pierce y Saussure y las diferencias entre ambas tende',
        'rae': [],
        'conceptuales': ['I. Comunicación visual y su esquema II. Tipos de imágenes III. Aspectos connotativo y denotativo IV. Signo, significante, y significado V. Pictograma, ideograma VI. Indice, icono, símbolo VII. Alfabetidad visual VIII. Esquema de transmisión y estilo de comunicación de la imagen IX. Proceso de creación de los signos visuales y audiovisuales.'],
        'procedimentales': ['Identificar las relaciones del signo, su contexto, los elementos de la composición pictórica.', 'Reconocer diversos tipos de imágenes según su función comunicativa, en obras de distintos estilos y períodos.', 'Emplear de forma adecuada dive rsos tipos de signos según su esquema de transmisión.', 'Interpretar con fluidez mensajes visuales y creaciones de la plástica, en el marco del autor, su cultura y su época.', 'Plan de estudio de la Mención Artes Visuales Dirección de la Modalidad en Artes', 'Crear un sistema de signos siguiendo proceso de investigación, esquemas , forma y estructuración del signo, retícula para construcción del signo.'],
        'actitudinales': ['Actitud de responsabilidad social y ética profesional en la obra visual.'],
    },
    'Dibujo Artístico': {
        'modulo': 'Bachillerato en Artes — Mención Artes Visuales',
        'horas': '4',
        'elemento_competencia': 'Dibuja a través de la observación y el análisis: paisajes , figuras anatómicas desde esqu emas simples y complejos relacionánd o los con entornos reales o imaginarios representados con las distintas técnicas de dibujo en los distintos proyectos.',
        'rae': ['Diferencia los distintos paisajes, estilos de dibujo, las técnicas y materiales. Desarrolla la expresión gráfico -analítica en las técnicas de lápiz grafito, carboncillo y sanguina así, como su aplicación a la resolución de problemas.', 'Hace uso de las habilidades para la percepción y análisis de la forma, textura y la materia.', 'Domina la representación de la perspectiva, proporción, composición, textura y efecto de luz y sombra en paisajes.', 'Representa composiciones de rostros con proporción y volumen desde distintos ángulos (frente, tres cuartos y perfil).', 'Dibuja car icaturas exagerando y manipulando las proporciones de los rasgos faciales de un rostro mostrando personalidades claras sin perder el parecido.', 'Realiza proyectos colectivos que involucren la composición de rostros y paisajes.', 'Argumenta acerca de los aspec tos generales y elementos característicos del dibujo anatómico, su relevancia y evolución desde el principio de la historia del arte hasta los tiempos actuales.', 'Construye la figura humana a través de esquemas básicos que permiten elaborar bocetos simples tomando en consideración la proporción, el encaje y el equilibrio.', 'Coloca la figura humana en diferentes perspectivas por medio del dibujo y toma en cuenta el punto de vista, la profundidad y el escorzo.', 'Realiza estudios de dibujo de las extremidades d el cuerpo humano de forma proporcionada según el punto de vista o tipo de cuerpo.', 'Interpreta las figuras humanas a través de esquemas de movimiento, síntesis y gestos corporales.', 'Aplica los efectos de la luz y la sombra a las figuras humanas tomando en consideración la dirección y colocación de las mismas.', 'Añade vestuarios a las figuras humanas con atención a los pliegues y arrugas que se producen en ellos.', 'Dibuja partiendo de la observación y el análisis de las figuras humanas al natural.', 'Explorar crea tivamente las posibilidades de representación del dibujo anatómico aplicando las diversas técnicas, materiales, instrumentos y soportes para plasmar su lenguaje propio.'],
        'conceptuales': ['El Paisaje rural, Composición: La división del marco.', 'Cambio de perspectiva .', 'La perspectiva árboles.', 'La textura y efecto .', 'Formas de árboles .', 'Materiales para los bosquejos .', 'A gran escala .', 'Composición: la selección .', 'Licencias con el paisaje .', 'Inventar paisajes .', 'El paisaje como diseño .', 'El paisaje urbano .', 'Visita a la ciudad .', 'La perspectiva de un punto .', 'La perspectiva de dos puntos .'],
        'procedimentales': ['Manejar las técnicas de: de grafi to, carboncillo, sanguina.', 'Dibujar paisajes y componer paisajes con cambios de perspectivas tanto rurales como urbanas.', 'Representar visualmente la forma de la cabeza, rasgos faciales y la expresión desde distintos ángulos (de frente, tres cuartos y perfil)', 'Interpretar y producir bosquejos rápidos y espontáneos.', 'Dibujar y componer retratos y auto retratos con volumen.', 'Interpretar a partir de modelos reales con volumen .', 'Plan de estudio de la Mención Artes Visuales Dirección de la Modalidad en Artes', 'Manejar las técnicas de: grafito, carboncillo, sanguina.', 'Estructurar los esque letos y esquemas básicos de dibujo anatómico.', 'Preparar bocetos.', 'Realizar los pasos para el encajado y proporción', 'Integrar la musculatura al dibujo anatómico.', 'Dibujar las extremidades de la figura humana.', 'Elaborar patrones y esquemas de movimiento.', 'Estudiar la luz y la sobra en el dibujo anatómico.'],
        'actitudinales': ['Importancia de la concentración durante la ejecución de un trabajo.', 'Desarrollo de habilidades psicomotoras, creativa s y originalidad. \uf0b7 Prepara correctamente los diferentes tipos de soportes.', 'Realiza veladuras, manchas y empastes siguiendo un proceso correcto de ejecución.', 'Pinta al óleo paisajes, marinas, bodegones y retratos de figuras con modelos mascu linos y femeninos vivos (al natural).', 'Realiza auto retratos.', 'Elabora pinturas relacionando la figura fonda.', 'Usa la espátula y los materiales extra pictóricos logrando distintos efectos en sus obras.', 'Utiliza el dripping y modeling en sus pinturas.', 'Aplica l a técnica del puntillismo en un proyecto pictórico.', 'Realiza pinturas abstractas y neo figurativas con estilos vanguardistas.', 'Logra valoraciones de luz y sombras en los cuadros.', 'Crea proyectos pictóricos haciendo uso de la originalidad y creatividad.', 'Plan de estudio de la Mención Artes Visuales Dirección de la Modalidad en Artes', 'Muestra sensibilidad, utiliza la introspección y la concentración.', 'Sentido de la observación, la percepción, el análisis de las formas y las proporciones.'],
    },
    'Pintura y Creatividad': {
        'modulo': 'Bachillerato en Artes — Mención Artes Visuales',
        'horas': '4',
        'elemento_competencia': 'Expresa mediante la pintura: formas, colores, líneas, tonalidades, texturas, paisajes, bodegones, figura humana y tema s libres, a través del uso de diversas técnicas y estilos pictóricos.',
        'rae': [],
        'conceptuales': ['I. La pintura acrílica, característica y usos. II. La composición del paisaje urbano y rural. III. El bodegón y su composición. IV. Pintura al natural. V. Estudios de fondos.', 'Plan de estudio de la Mención Artes Visuales Dirección de la Modalidad en Artes', 'VI. Estilos en la pintura. VII. La pintura al óleo, propiedades y caract erísticas. VIII. Tipos de formatos, montaje, preparación e imprimación sobre diversos soportes. IX. Disolventes, herramientas, barnices. X. Introducción de La figura humana en la pintura. XI. El canon de la figura humana. XII. Perspectiva de la figura humana en la pintura. XIII. Relación figura humana y fondo. XIV. El retrato y autorretrato. XV. Aplicación Claroscuros, texturas y pliegues. XVI. La pintura simbólica y abstracta. XVII. Técnica mixta y estilos pictóricos vanguardistas.'],
        'procedimentales': ['Manejar la paleta de colores en pintura acrílica.', 'Realizar un paisaje con pintura acrílica.', 'Preparar un bodegón con pintura acrílica.', 'Realizar estudios de fondo.', 'Aplicar estilos artísticos.', 'Mezclar los colores con limpieza y armonía, en tonalidades diversas, y con sentido expresivo y simból ico.', 'Preparar correctamente los diferentes tipos de soportes.', 'Realizar veladuras, manchas y empastes siguiendo un proceso correcto de ejecución.', 'Pintar al óleo paisajes, marinas, bodegones y retratos de figuras con modelos masculinos y femeninos vivos (al natural).', 'Realizar auto retratos.', 'Elaborar pinturas relacionando la figura y el fondo.', 'Usar la espátula y los materiales extra pictóricos.', 'Aplicar el dripping en el soporte.', 'Utilizar el modeling paste para conseguir diversas texturas.', 'Aplicar la técnica del puntillismo en un proyecto pictórico.'],
        'actitudinales': ['Importancia de la concentración durante la ejecución de un trabajo.', 'Desarrollo de habilidades psicomotoras, creativas y originalidad.', 'Muestra sensibilidad, utiliza la introspección y la concentración.', 'Sentido de la observación, la percepción, el análisis de las formas y las proporciones.', 'Plan de estudio de la Mención Artes Visuales Dirección de la Modalidad en Artes'],
    },
    'Modelado I': {
        'modulo': 'Bachillerato en Artes — Mención Artes Visuales',
        'horas': '3',
        'elemento_competencia': 'Aplica técnicas bás icas del modelado en arcilla y en la talla representando figuras geométricas sencillas que reproduce siguiendo procedimientos de moldeado (tacelado ) y vaciado. moldes, hasta alcanzar un positivo en yeso. Saberes actitudinales: \uf0b7 Paciencia, cuidado y pulcritud en el desarrollo de los procesos. Responsabilidad y perseverancia. Trabajo en equipo. Rango de aplicación Confección de paneles con molduras en bajo y alto relieve del arte decorativo. Industrias culturales y/o artesanales. Escenografía y Mock Up’s. Evidencias de desempeño. Presenta tres ejemplos de modelado , termina',
        'rae': [],
        'conceptuales': ['I. Breve Introducción a la historia de la escultura y del modelado. II. La escultura en el plano y en el espacio: III. El Bajo relieve IV. El Alto relieve V. El bulto. VI. Aspectos técnicos del modelado. VII. Directa: tallar, esculpir. VIII. Indirecta: modelado, tacelado, vaciado y fundi do. IX. Mixtas: modelado directo, ensamblado y otros. X. Herramientas de cada proceso. XI. Técnicas de talla. Esculpir la piedra, el granito y el mármol. XII. Fundición en hierro bronce o aluminio. La cera perdida. XIII. La masilla, el cemento, el yeso; directos o por vaciado.'],
        'procedimentales': ['Conoce y experimenta con la plasticidad de la arcilla : Tritura , amasa, alisa, carga.', 'Conoce y usa correctamente las herramientas del escultor.', 'Realiza ejercicios de modelado copiando frisos en alto relieve y en bajo relieve, así como modela figuras geométricas elementales.', 'Experimenta las características técnicas del ye so realizando un molde o tacel y reproduce por vaciado en yeso, los frisos modelados.', 'EJERCICIOS DE MODELADO ESPACIALES:', 'Plan de estudio de la Mención Artes Visuales Dirección de la Modalidad en Artes', 'Modela Una columna, estriada, con o sin tope en arcilla 10cm x 10cm x 45cm.', 'Copia por vaciado en yeso la columna.', 'MODELA 3 Formas geométricas básicas (cono, cubo, poliedro) s/ plano inclinado. 25cm x 30cm x 25cm.', 'Copia por vaciado en yeso usando taceles.', 'EJERCICIO DE TALLA :', 'Talla un bloque de yeso de 10cm x 20cm x 30cm.'],
        'actitudinales': ['Paciencia, cuidado y pulcritud en el desarrollo de los procesos. Responsabilidad y perseverancia. Trabajo en equipo.'],
    },
    'Diseño Bi y Tridimensional': {
        'modulo': 'Bachillerato en Artes — Mención Artes Visuales',
        'horas': '4',
        'elemento_competencia': 'Representa gráficamente por medio de técnicas manuales y tecnologías digitales, proyectos sencillos de diseño bidimensional, y construye objetos y/o espacios 238 Plan de estudio de la Mención Artes Visuales Dirección de la Modalidad en Artes tridimensionales, así como proyectos arquitectónicos sencillos con planta general, planta amueblad a y elevaciones, en varias escalas, aplicando los códigos técnicos de arquitectura y el diseño.',
        'rae': [],
        'conceptuales': ['Pintura Mural, contexto histórico, evolución, características y principales exponentes.', 'Los murales más importantes de la historia; Capilla Sixtina. Indicadores de logros', 'Explica la historia, evolución y características de la pintura mural.', 'Identifica los principales exponentes de la pintura mural y sus obras más relevantes.', 'Plan de estudio de la Mención Artes Visuales Dirección de la Modalidad en Artes', 'Carácter de la pintura mural: decorativo y arquitectónico.', 'La Pintura Mural materiales, técnicas y evolución.', 'La pintura mural y otras intervenciones murales artísticas.', 'La pintura mural y las intervenciones murales de arte público: El grafiti valor socioc ultural y expresivo.', 'Función comunicativa del mural en la actualidad.'],
        'procedimentales': ['Aplicar técnicas manuales de delineación, para la representación de proyectos bidimensionales .', 'Explorar los diferentes programas, sus comandos y herramientas, para la consecución de elementos bidimensionales en un proyecto simple .', 'Generar presentaciones de 2D y 3D proporci onadas a escala, para propiciar su impresión e interpretación posterior correctas .', 'Crear imágenes fotorrealistas de los modelos tridimensionales, para tener una idea más cercana al objeto representado, utilizando recursos digitales y/o convencionales .', 'Estructurar adecuadamente los proyectos tridimensionales a través de una lógica de ordenamiento, para lograr una propuesta que pueda ser entendible por otros .', 'Plan de estudio de la Mención Artes Visuales Dirección de la Modalidad en Artes', 'Realizar acotamientos que permitan describir con precisión el proyecto, adaptándose a la normativ a en diversas escalas .', 'Creación, uso edición de librerías de detalles y elementos constructivos, para abreviar tiempos y garantizar uniformidad en la preparación de proyectos representados tridimensionalmente .', 'Emplear los diferentes métodos y comandos de edición, para la creación de volúmenes, juego de luces, sombras (entre otros), para la consecución de elementos tridimensionales en un proyecto .'],
        'actitudinales': ['Interés, observación y orden .'],
    },
    'Pintura Mural y Decorativa': {
        'modulo': 'Bachillerato en Artes — Mención Artes Visuales',
        'horas': '6',
        'elemento_competencia': 'Realiza la pintura mural artística mediante haciendo uso de las técnicas clásicas o contemporáneas de su elección: al fresco, al graffitti, la acrílica y -o la piroxilina, así como diversos acabados del muro con fines decorativos. Resultado s del Aprendizaje Esperados \uf0b7 Identifica los diversos momentos históricos del mural y los materiales usados progresivamente. \uf0b7 Investiga sobre todos los estilos y tendencias de la pintura mural. \uf0b7 Visita localidades con murales para estudiar las temáticas y técnicas empleadas. \uf0b7 Desarrolla un proyecto colectivo usando los procedimientos aprendidos. Contenid',
        'rae': [],
        'conceptuales': ['I. Pintura Mural, contexto histórico, evolución, características y principales exponentes. II. Los murales más importantes de la historia; Capilla Sixtina.', 'III. Carácter de la pintura mural: decorativo y arquitectónico. IV. La Pintura Mural materiales, técnicas y evolución. V. La pintura mural y otras intervenciones murales artísticas. VI. La pintura mural y las intervenciones mu rales de arte público: El grafiti valor sociocultural y expresivo. VII. Función comunicativa del mural en la actualidad.'],
        'procedimentales': ['Estudiar el espacio de trabajo, sus condiciones estructurales y su carácter efímero o duradero.', 'Aplicar técnica s de pintura mural decorativa, para efectos en espacios interiores.', 'Aplicar técnicas de pintura mural al exterior.', 'Producir composiciones murales mediante técnicas de:', 'Temple de huevo sobre muros.', 'Técnicas de pintura mural al seco: Pintura mural a la c aseína, encáustica, óleo, pintura acrílica y piroxilina.', 'Realizar un proyecto de mural en una representación a escala.', 'Reflejar el diseño del proyecto al muro.'],
        'actitudinales': ['La importancia de la pintura Mural como exponente de nuestra idea estétic a.', 'Apreciar el entorno espacial urbano y arquitectónico.', 'Disciplina y orden para llevar acabo los procesos de la pintura mural.', 'Actitud creativa e innovadora', 'Cuidado medioambiental y personal.', 'Plan de estudio de la Mención Artes Visuales Dirección de la Modalidad en Artes', 'Ética y compromiso social.'],
    },
    'Modelado II': {
        'modulo': 'Bachillerato en Artes — Mención Artes Visuales',
        'horas': '4',
        'elemento_competencia': 'Modela formas anatómicas y figuras abstractas o concretas, abiertas o cerradas, en reposo o movimiento, y las reproduce mediante técnicas de vaciado en yeso o cemento.',
        'rae': [],
        'conceptuales': ['Morfología:', 'Lo geométrico vs. lo orgánico.', 'Anatomía básica músculo -esquelética.', 'La estructura interna y su dinámica de fuerzas.', 'Las proporciones anatómicas.', 'Plan de estudio de la Mención Artes Visuales Dirección de la Modalidad en Artes', 'La divina proporción. Espiral Áurea.', 'Análisis de obras anatómicas destacadas, de la historia del arte clásica. Miguel Ángel, Donatello, Rodín, entre otros.', 'El concepto de la espiral áurea, la proporción y su aplicación en la escultura.', 'Las figuras cerradas , las abiertas y las estáticas en movimiento.', 'Estudiar la estructura axial en las obras básicas (parado, sentado, acostado).', 'Estudio de la figura cerrada', 'La esfinge.', 'El Chac Mool.', 'Un esclavo de Miguel Ángel'],
        'procedimentales': ['Construye armazones para sostener la estructura de figuras de cabeza, tronco y extremidades, aplicando ejes y vectores de direcciones.', 'Modela piezas figurativas:', 'Una cabeza.', 'Una figura humana sentada o parada.', 'Una figura reclin ada sobre un plano inclinado.', 'Planea la ejecución del tacelado múltiple hasta completar un molde con registros.', 'Montaje y armado de moldes por taceles.', 'Reproducción por vaciado en yeso de 1; 2; 3.', 'Desmoldado de taceles.', 'Realiza un compás áureo para comprender la lógica constructiva de algunas proporciones.', 'Realiza ejercicios de medición y usos para una mejor comprensión de las proporciones.', 'Bocetar fotografías de esculturas predeterminadas buscando proporciones áureas y marcando ejes, pesos, balance, masa, bulto y vacío.', 'Realización de bocetos escultóricos rápidos, para adiestrarse con ejes y proporciones.', 'Plan de estudio de la Mención Artes Visuales Dirección de la Modalidad en Artes', 'Desarrollar un plan personal con dos proyectos diferentes, A y B, donde el maestro seleccionará las obras a copiar del stock de calcos que encuentre según el caso. El stock será de 6 modelos a copiar y seguir, predeterminados por el maestro. A.- Modelado de figura parada, apoyada en reposo (selecciona uno de 3 predeterminados) en caso de contar con modelo vivo, no habrá múltiple selección.'],
        'actitudinales': ['Desarrollar la inteligencia visual y espacial.', 'Desarrollar la sensibilidad crítica en la percepción del entorno y de la naturaleza.', 'Fomentar el compañerismo, la organización y el trabajo en grupo.', 'Velar por el cuidado de lo personal, el equipo y las herramientas.', 'Plan de estudio de la Mención Artes Visuales Dirección de la Modalidad en Artes', 'Fomentar la paciencia con los procesos, el entorno ambiental y las condiciones del trabajo.', 'Se entrega y enfoca en la observación de la figura humana como un todo . Se concentra en su trabajo y en los procesos. Trabaja en equipo. Cuida el medio ambiente. Lleva adelante el trabajo hasta conseguir sus objetivos con prolijidad y perseverancia. Internaliza al modelado como una forma de expresarse.', 'Colabora con sus compañeros ayudando durante el proceso de corte de materiales, cuida y se maneja de manera prudente en el uso de las herramientas.', 'Respeta los lugares de trabajo.', 'Es ordenado y consistente durante los procedimientos.'],
    },
    'Dibujo Arquitectónico Digital': {
        'modulo': 'Bachillerato en Artes — Mención Artes Visuales',
        'horas': '4',
        'elemento_competencia': 'Diseña proyectos culturales, emprendedores y contemporáneos de producción plástica creativa, con una imagen corporativa y la exploración creadora del estilo propio para la exposición y venta de sus creaciones plásticas, aplicando estrategias de mercadeo, liderazgo y toma de decisiones en equipos de simulación empresarial, en el marco de la promoción y venta del producto artístico, asumiendo una actitud emprendedora con responsabilidad social y financiera.',
        'rae': [],
        'conceptuales': ['I. La representación gráfica, 2D las formas y sus vistas en planta y elevación. II. Signos y símb o los de la representación gráfica en planos arquitectónicos . III. Concepto de proporción aplicado al diseño de objetos y espacios . IV. Concepto de escala. Escala natural, escala de reducción y escala de ampliación V. Clases y grosores de líneas según el uso y la escala utilizar. VI. Contenido de la tarjeta de Pres entación. VII. Interfaz del usuario, Menú de inicio, creación del entorno VIII. Acotación de las medidas. IX. Formas básicas para dibujar objetos en 2D X. Elementos constructivos y su', 'Plan de estudio de la Mención Artes Visuales Dirección de la Modalidad en Artes', 'XI. Visión tridimensional en el entorno CAD: fundamentos de la perspec tiva axonométrica. XII. Introducción de las dimensiones o medidas . XIII. Sistema de medidas .', 'Procedimentales: ● Maneja las herramientas digitales del programa asistido por computadora CAD. ● Administra archivos de dibujo y configura su sistema de unidades ● Ejecuta los diversos comandos del programa, para construir figuras en 2D ● Realiza planos digitales de objetos geométricos sencillos representados en planta y en elevación ● Ejecuta a escala, planos arquitectónicos sencillos con acotaciones. ● Maneja las herra mientas digitales del programa asistido por computadora. ● Domina la herramienta extrusión, y región, modelado 3D, presionar y tirar. ● Ejecuta los diversos comandos del prog', 'Actitudinales', 'Receptividad .', 'Interés por la representación visual .', 'Percepción y visualización .'],
        'procedimentales': ['Emplear técnicas de imaginación y visualización de imágenes y sensaciones interiores .', 'Expresar las ideas personales por medio del dibujo, pintura, grabado, fotografía, la escultur a, el ensamblaje, y otras técnicas.', 'Crear una propuesta visual con estilo personal', 'Planear la ejecución de la propuesta artística', 'Calcular presupuesto financiamiento y plan de gastos del negocio.', 'Ejecutar estrategias de mercadeo con el empleo de la Web 2.0', 'Actitudes y valores', 'Creatividad .', 'Curiosidad .', 'Introspección .', 'Responsabilidad social .', 'Actitud emprendedora y creatividad .', 'Responsabilidad financiera', 'Solidaridad .', 'Disposición a la innovación y a la experimentación. el empleo de al menos una de las técnicas pictóricas.'],
        'actitudinales': ['Creatividad .', 'Curiosidad .', 'Introspección .', 'Responsabilidad social .', 'Actitud emprendedora y creatividad .', 'Responsabilidad financiera', 'Solidaridad .', 'Disposición a la innovación y a la experimentación. el empleo de al menos una de las técnicas pictóricas.', 'Representa con efec tividad composiciones tridimensionales usando al menos una de las técnicas escultóricas.', 'Se relaciona consigo mismo propiciando el autoconocimiento.', 'Aplica su imaginación expresando imágenes mentales personales', 'Produce una propuesta visual propia, original, empleando al menos una de las técnicas de las artes visuales contemporáneas .', 'Planifica la ejecución de su propuesta artística .', 'Calcula su presupuesto, opciones de financiamiento y plan de gastos del negocio.', 'Mercadea su arte y obtiene vinculaciones productivas, capital social, con el empleo de las redes sociales.'],
    },
    'Proyecto Empr endedor de Arte Contemporáneo': {
        'modulo': 'Bachillerato en Artes — Mención Artes Visuales',
        'horas': '5',
        'elemento_competencia': 'Diseña proyecto s cultural es, emprendedor es y contemporáneo s de producción plástica creativa, con una imagen corporativa y la exploración creadora del estilo propio para la exposición y v enta de sus creaciones plásticas, aplicando estrategias de mercadeo, liderazgo y toma de decisiones en equipos de simulación empresarial, en el marco de la promoción y venta del producto artístico, asumiendo una actitud emprendedora con responsabilidad soc ial y financiera.',
        'rae': [],
        'conceptuales': ['Pensamiento ideológico, ecléctico y multicultural del arte contemporáneo.', 'Las Manifestaciones y tendencias del arte objetual, las instalaciones artísticas, el arte conceptual, happening y la performance.', 'Modalidades procesuales en las instalaciones artísticas (Arte Minimal ista, Arte Povera y Land Art)', 'Arte Conceptual, ideas, sistema y proceso.', 'Glosario de términos del arte contempor áneo.', 'Proyectos creativos contemporáneos (idealización, gestión, producción.)', 'Análisis de productos fotográficos como documentación', 'El arte y las nuevas tecnologías (El video arte, Net Art)', 'Plan de estudio de la Mención Artes Visuales Dirección de la Modalidad en Artes', 'El Arte urbano e implicaciones sociales, ambientales, lúdicas id entidad y memoria.', 'Plan museográfico de espacios de exposición.'],
        'procedimentales': ['Describir objetos como un documento testimonial (A rte Objetual)', 'Ensamblar objeto común y elaborar un Radymade.', 'Construir objetos artísticos (minimalista, Povera) .', 'Dominar las herramientas de montaje de la instalación artística.', 'Producir instalación artística con creaciones multimedios (video -instalación, pintura y esculto -instalación, instalación -sonora, performance –instalación.', 'Utilizar fotografías conceptuales e n la preparación de proyectos.', 'Pinta y dibuja conceptualmente.', 'Realizar montaje y apropiación de imágenes conceptuales.', 'Preparar portafolio de imágenes y o documentación de obra realizadas.', 'Utilizar la fotografía como documentación del proceso crítico y c reativo, a través del análisis de sus contenidos visuales.', 'Crear una propuesta visual con estilo personal y autónomo.', 'Planear la ejecución de propuestas artísticas lúdica, social y crítica.', 'Reproducir montaje sensorial de creaciones permanente y efímera.', 'Calcular el presupuesto, financiamiento y plan de gastos del proyecto.', 'Ejecutar estrategias de mercadeo con el empleo de la Web 2.0.'],
        'actitudinales': ['Valora la obra como documento testimonial artístico e histórico.', 'Critica reflexiva ante el proceso de aprendizaje en el contexto de una realidad cercana.', 'Participa en aspecto lúdico -creativo y sensorial como un proceso intelectual.', 'Pensamiento lógico abstracto en la variedad de la plástica creativa y perceptiva. ( arte-vida)', 'Fomentar hábitos de pensamiento crítico, lógico y creativo.', 'Responsabilidad social y financiera en el proceso de aprendizaje.', 'Actitud emprendedora y creativa.', 'Disposición a la innovación en presentación de multimedia.', 'Trabajo en equipo, cooperación y solidaridad.', 'Ser tolerante y solidario a proyecto desarrollado por una crítica abierta y participativa en el aula por parte de todos sus miembros .'],
    },
    'Entrenamiento Para Talleres De Expresión Plástica': {
        'modulo': 'Bachillerato en Artes — Mención Artes Visuales',
        'horas': '4',
        'elemento_competencia': '',
        'rae': [],
        'conceptuales': ['I. Etapas de desarrollo psicosocial y expresivo de niño y adolescentes.', 'Plan de estudio de la Mención Artes Visuales Dirección de la Modalidad en Artes', 'II. Teoría de la educación: las tendencias de la educación en el arte, con énfasis en el constructivismo el enfoque constructivista socio -histórico cultural, y el desarrollo de las competencias de la creatividad. III. Fundamentos sobre la planeación de los aprendiza jes en una unidad didáctica. Categorías de la Didáctica. IV. Métodos y estrategias de aprendizaje en la expresión plástica. V. Estrategias de seguimiento al desarrollo expresivo.'],
        'procedimentales': ['Argumenta la importancia de la educación plástica en el d esarrollo psicosocial del niño y el adolescente, en el marco de las principales tendencias formativas en el arte.', 'Realiza la planeación de una unidad didáctica con actividades de expresión creadora infantil, en el marco del diseño curricular.', 'Aplica metodo logía del proceso de enseñanza -aprendizaje de la expresión plástica infantil en una clase de un taller en su comunidad.'],
        'actitudinales': ['Valoración del arte infantil.', 'Amor por la infancia.', 'Responsabilidad.'],
    },
}

ALIAS_ARTES_VISUALES = {}

import re as _re
import unicodedata as _ud

def _firma_artes_visuales(s: str) -> str:
    """Firma sin acentos/espacios para búsqueda tolerante a kerning del PDF."""
    nfkd = _ud.normalize('NFKD', s)
    sin_tilde = ''.join(c for c in nfkd if not _ud.combining(c))
    return _re.sub(r'[^a-zA-Z0-9]', '', sin_tilde).lower()

_IDX_ARTES_VISUALES = {_firma_artes_visuales(k): k for k in CURRICULUM_ARTES_VISUALES}

def get_asignatura_artes_visuales(nombre: str) -> dict:
    canon = ALIAS_ARTES_VISUALES.get(nombre, nombre)
    result = CURRICULUM_ARTES_VISUALES.get(canon) or CURRICULUM_ARTES_VISUALES.get(nombre)
    if not result:
        firma = _firma_artes_visuales(nombre)
        orig_key = _IDX_ARTES_VISUALES.get(firma)
        if orig_key:
            result = CURRICULUM_ARTES_VISUALES.get(orig_key)
    return result or {}

def formatear_contexto_artes_visuales(nombre: str) -> str:
    d = get_asignatura_artes_visuales(nombre)
    if not d: return ""
    partes = []
    if d.get("elemento_competencia"):
        partes.append("ELEMENTO DE COMPETENCIA:\n" + d["elemento_competencia"])
    if d.get("rae"):
        partes.append("RAE (Resultados de Aprendizaje Esperados):\n" + "\n".join("- " + r for r in d["rae"]))
    if d.get("conceptuales"):
        partes.append("SABERES CONCEPTUALES:\n" + "\n".join("- " + c for c in d["conceptuales"]))
    if d.get("procedimentales"):
        partes.append("SABERES PROCEDIMENTALES:\n" + "\n".join("- " + p for p in d["procedimentales"]))
    if d.get("actitudinales"):
        partes.append("SABERES ACTITUDINALES:\n" + "\n".join("- " + a for a in d["actitudinales"]))
    return "\n\n".join(partes)
